# Generated by Django 4.1 on 2022-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0004_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
    ]
