# Generated by Django 4.1 on 2022-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0005_watchlist_avg_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
